acme_test_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeTestBundle:Default:index }

acme_test_apigraph:
    path:     /apigraph
    defaults: { _controller: AcmeTestBundle:Apigraph:index }

acme_test_apigraph_referrer:
    path:     /apigraph/referrer
    defaults: { _controller: AcmeTestBundle:Apigraph:referrer }